using System.ComponentModel.DataAnnotations;
using NetEscapades.EnumGenerators;

namespace SCALE.Enums;

[EnumExtensions]
public enum EItemNames
{
    Longsword,
    Warhammer,
    Crossbow,
    Mace,
    Halberd,
    Dagger,
    Flail,
    Poleaxe,
    Battleaxe,
    Morningstar,
    Greatsword,
    Lance,
    Quarterstaff,
    Javelin,
    Rapier,
    Bow,
    Shield,
    Scimitar,
    Falchion,

    [Display(Name = "Leather Helmet")] LeatherHelmet,
    [Display(Name = "Leather Chestpiece")] LeatherChestpiece,
    [Display(Name = "Leather Leggings")] LeatherLeggings,
    [Display(Name = "Leather Boots")] LeatherBoots,
    [Display(Name = "Chainmail Coif")] ChainmailCoif,
    [Display(Name = "Chainmail Hauberk")] ChainmailHauberk,
    [Display(Name = "Chainmail Leggings")] ChainmailLeggings,
    [Display(Name = "Chainmail Boots")] ChainmailBoots,
    [Display(Name = "Iron Helmet")] IronHelmet,
    [Display(Name = "Iron Chestplate")] IronChestplate,
    [Display(Name = "Iron Leggings")] IronLeggings,
    [Display(Name = "Iron Boots")] IronBoots,
    [Display(Name = "Steel Helmet")] SteelHelmet,
    [Display(Name = "Steel Chestplate")] SteelChestplate,
    [Display(Name = "Steel Leggings")] SteelLeggings,
    [Display(Name = "Steel Boots")] SteelBoots,
    
    
    [Display(Name = "Elixir of Healing")] ElixirOfHealing,
    [Display(Name = "Potion of Invisibility")] PotionOfInvisibility,
    [Display(Name = "Mana Crystal")] ManaCrystal,
    [Display(Name = "Firebreath Ale")] FirebreathAle,
    [Display(Name = "Ambrosia Nectar")] AmbrosiaNectar,
    [Display(Name = "Dragon's Blood Wine")] DragonsBloodWine,
    [Display(Name = "Trollbane Tonic")] TrollbaneTonic,
    [Display(Name = "Feywild Honey")] FeywildHoney,
    [Display(Name = "Ghost Pepper Elixir")] GhostPepperElixir,
    [Display(Name = "Manticore Milk")] ManticoreMilk,
    [Display(Name = "Moonlit Dewdrops")] MoonlitDewdrops,
    [Display(Name = "Celestial Essence")] CelestialEssence,
    [Display(Name = "Wyrmwood Brew")] WyrmwoodBrew,
    [Display(Name = "Phoenix Feather Tea")] PhoenixFeatherTea,
    [Display(Name = "Enchanted Truffle")] EnchantedTruffle,
    [Display(Name = "Faerie Fruit")] FaerieFruit,
    [Display(Name = "Basilisk Eye Brew")] BasiliskEyeBrew,
    [Display(Name = "Stardust Loaf")] StardustLoaf,
    [Display(Name = "Ogre's Strength Ale")] OgresStrengthAle,
    [Display(Name = "Siren's Song Ale")] SirensSongAle,
    [Display(Name = "Shadowfire Whiskey")] ShadowfireWhiskey,
    [Display(Name = "Griffin's Roar Brew")] GriffinsRoarBrew,
    [Display(Name = "Pixie Plum Wine")] PixiePlumWine,
    [Display(Name = "Wyrmscale Draught")] WyrmscaleDraught,
    [Display(Name = "Unicorn Tear Elixir")] UnicornTearElixir,
    [Display(Name = "Gorgon's Gaze Mead")] GorgonsGazeMead,
    [Display(Name = "Nymph's Nectar")] NymphsNectar,
    [Display(Name = "Lichbane Elixir")] LichbaneElixir,
    [Display(Name = "Goblin's Gold Stout")] GoblinsGoldStout,
    [Display(Name = "Frostberry Nog")] FrostberryNog,
    [Display(Name = "Angel's Kiss Mead")] AngelsKissMead,
    [Display(Name = "Chimera Chili")] ChimeraChili,
    [Display(Name = "Sorcerer's Brew")] SorcerersBrew,
    [Display(Name = "Minotaur Muscle Mead")] MinotaurMuscleMead,
    [Display(Name = "Starlight Biscuit")] StarlightBiscuit,
    [Display(Name = "Gargoyle Gravy")] GargoyleGravy,
    [Display(Name = "Elfroot Elixir")] ElfrootElixir,
    [Display(Name = "Demon's Delight")] DemonsDelight,
    [Display(Name = "Valkyrie's Vigor")] ValkyriesVigor,
    [Display(Name = "Enchanter's Infusion")] EnchantersInfusion,
    [Display(Name = "Sphinx's Secret")] SphinxsSecret,
    [Display(Name = "Gnomish Grog")] GnomishGrog,
    [Display(Name = "Moonlit Muffin")] MoonlitMuffin,
    [Display(Name = "Viper's Venom Vial")] VipersVenomVial,
    [Display(Name = "Witch's Brew")] WitchsBrew,
    [Display(Name = "Paladins Pint")] PaladinsPint,
    [Display(Name = "Goblins Grog")] GoblinsGrog,
    [Display(Name = "Pegasus Plum Brandy")] PegasusPlumBrandy,
    [Display(Name = "Feywild Fizz")] FeywildFizz,
    [Display(Name = "Moonshadow Mint Tea")] MoonshadowMintTea,
}